#!/bin/python3

# Script d'interface entre INGInious et des tests unitaires écrits à l'aide de CUnit
# Auteurs : Mathieu Xhonneux, Anthony Gégo
# Licence : GPLv3
import subprocess, shlex, re, os, yaml
import inginious 
import pexpect as px
from e2e import e2e, check_maker, make
from utest import utest,ureport
os.chdir("student")]

scores=[0]*5

codename='code1'
template='code1.cc.tpl'
ext="cc"
tag_num="1"
tag="add_function"
order=[{'expect': ':', 'send': 'a'}, {'expect': ':', 'send': 'Curry'}, {'expect': ':', 'send': 'L'}, {'expect': ':', 'send': 'n'}, {'expect': ':', 'send': 'd'}]
ans="ans1"
e2etest=True

make(ans)
check=check_maker(ans,order)
scores[0]=utest(template,codename,ext,tag_num,tag,e2etest,order,check)
ureport(scores)
