#!/bin/bash

getinput "thecode" > student/student_code.cpp
make student/student_code
output=$(./student/student_code)
out="$output"
ans=$'a\na a\na a a\na a a a\na a a a a'  # bash syntax sucks
if [ "$output" = "$ans" ]; then
    feedback-result success
    feedback-msg -m "Your program is correct."
else
    feedback-result failed
    feedback-msg -m "Your program is incorrect: possible newline issues."
fi

# clean student files
output=0
rm -r student/student_code*  